/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import business.accountdirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author Ram
 */
public class AccMngr extends javax.swing.JPanel {

       private accountdirectory accDirect; 
       private JPanel cardlayout;

    AccMngr(JPanel cardlayout, accountdirectory accDirect) {
        initComponents();
        this.cardlayout= cardlayout;
    this.accDirect = accDirect;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnCreateAccount = new javax.swing.JButton();
        BtnManageAccount = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        BtnCreateAccount.setText("Create Account");
        BtnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateAccountActionPerformed(evt);
            }
        });

        BtnManageAccount.setText("Manage Account");
        BtnManageAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnManageAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnCreateAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnManageAccount)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateAccountActionPerformed
        // TODO add your handling code here:
        create panel= new create(cardlayout, accDirect);
        cardlayout.add("create",panel); 
        CardLayout layout = (CardLayout) cardlayout.getLayout();
        layout.next(cardlayout);
               
        
    }//GEN-LAST:event_BtnCreateAccountActionPerformed

    private void BtnManageAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageAccountActionPerformed
        // TODO add your handling code here:
        ManagePanel panel = new ManagePanel(cardlayout, accDirect);
          cardlayout.add("ManagePanel",panel);
        CardLayout layout = (CardLayout) cardlayout.getLayout();
        layout.next(cardlayout);
        
        
    }//GEN-LAST:event_BtnManageAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreateAccount;
    private javax.swing.JButton BtnManageAccount;
    // End of variables declaration//GEN-END:variables
}
